exp_name: "copyright_image"
num_steps: 140000
data_dir: summer2winter_yosemite/trainA
checkpoints: "checkpoints"
saved_path: "saved_images"
run_path: "runs"
batch_size: 2
num_workers: 8
height: 256
width: 256
lr: 0.0001
l2_loss_scale: 1
l2_loss_ramp: 20000
l2_edge_gain: 10.0
l2_edge_ramp: 20000
l2_edge_delay: 60000
lpips_loss_scale: 1.0
lpips_loss_ramp: 20000
secret_loss_scale: 20.0
secret_loss_ramp: 2000
y_scale: 1.0
u_scale: 1.0
v_scale: 1.0
jpeg_quality: 25
jpeg_compression: True
random_blur: True
text_enhance: True
text_contents: ["@copyright", "copyright protection", "weibo", "bilibili", "tiktok", "douyin", "kuaishou", "twitter","fackbook", "facebook", "microsoft"]
jpeg_quality_ramp: 1000
pretrained: None